name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      # - name: Run test
      #   run: npm test
      #   env:
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB_HOST: ${{ secrets.DB_HOST }}
      #     DB_PORT: ${{ secrets.DB_PORT }}
      - run: npm run build
      - name: Zip files
        run: tar -cvf dist.tar ./dist/
      # https://stackoverflow.com/a/61236896/7270469
      # https://github.com/appleboy/scp-action
      - name: Deploy update file
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.LIVE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist.tar"
          target: ${{ secrets.DEPLOY_DIR }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ./dist && tar -xvf dist.tar -C ./dist
            rm dist.tar

